# Use official Python image
FROM python:3.10-slim

# Set workdir
WORKDIR /app

# Copy files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir flask flask-cors numpy scikit-learn keras tensorflow

# Expose port (Flask default)
EXPOSE 5000

# Run the app
CMD ["python", "cnnapp.py"]
