


export const CropData = [
  {
    id: 1,
    name: 'Bugday',
    category: 'Tahıl',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.5',
    climate: ['Ilıman', 'Yarı Kurak'],
    waterNeeds: 'Orta',
    growingSeason: 'Kış/İlkbahar',
    imageUrl:  require('../assets/images/Bugday.jpg'),
    description: 'Türkiye\'nin en önemli tahıl ürünlerinden biri olan buğday, ekmek ve unlu mamullerin temel hammaddesidir.'
  },
  {
    id: 2,
    name: 'Arpa',
    category: 'Tahıl',
    soilType: ['Killi', 'Kumlu'],
    phRange: '6.0-7.5',
    climate: ['Ilıman', 'Kurak'],
    waterNeeds: 'Düşük',
    growingSeason: 'Kış/İlkbahar',
    imageUrl: require('../assets/images/Arpa.jpg'),
    description: 'Hayvan yemi ve malt üretiminde kullanılan önemli bir tahıl ürünüdür.'
  },
  {
    id: 3,
    name: 'Misir',
    category: 'Tahıl',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '5.8-7.0',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Yüksek',
    growingSeason: 'Yaz',
    imageUrl: require('../assets/images/Misir.jpg'),
    description: 'Hem insan beslenmesinde hem de hayvan yemi olarak kullanılan önemli bir tahıl ürünüdür.'
  },
  {
    id: 4,
    name: 'Cavdar',
    category: 'Tahıl',
    soilType: ['Kumlu', 'Killi'],
    phRange: '5.5-7.0',
    climate: ['Soğuk', 'Ilıman'],
    waterNeeds: 'Düşük',
    growingSeason: 'Kış',
    imageUrl: require('../assets/images/Cavdar.jpg'),
    description: 'Soğuğa dayanıklı, fakir topraklarda yetişebilen bir tahıl ürünüdür.'
  },
  {
    id: 5,
    name: 'Yulaf',
    category: 'Tahıl',
    soilType: ['Killi', 'Kumlu'],
    phRange: '5.5-7.0',
    climate: ['Soğuk', 'Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'Kış/İlkbahar',
    imageUrl: require('../assets/images/Yulaf.jpg'),
    description: 'Besleyici değeri yüksek, hayvan yemi ve insan beslenmesinde kullanılan bir tahıl ürünüdür.'
  },
  {
    id: 6,
    name: 'Tritikale',
    category: 'Tahıl',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.5',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'Kış/İlkbahar',
    imageUrl: require('../assets/images/Tritikale.jpg'),
    description: 'Buğday ve çavdarın melezlenmesiyle elde edilen yeni bir tahıl türüdür.'
  },
  {
    id: 7,
    name: 'Kaplica_Bugdayi',
    category: 'Tahıl',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.5',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Düşük',
    growingSeason: 'Yaz',
    imageUrl: require('../assets/images/Kaplica_Bugdayi.jpg'),
    description: 'Sıcak ve kurak bölgelerde yetiştirilen özel bir buğday türüdür.'
  },

  // Baklagiller (Legumes)
  {
    id: 8,
    name: 'Nohut',
    category: 'Baklagil',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.5',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Düşük',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Nohut.jpg'),
    description: 'Protein açısından zengin, kuraklığa dayanıklı bir baklagil türüdür.'
  },
  {
    id: 9,
    name: 'Kuru_Fasulye',
    category: 'Baklagil',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Kuru_Fasulye.jpg'),
    description: 'Türk mutfağının vazgeçilmez protein kaynağı olan önemli bir baklagil türüdür.'
  },
  {
    id: 10,
    name: 'Mercimek',
    category: 'Baklagil',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.5',
    climate: ['Ilıman'],
    waterNeeds: 'Düşük',
    growingSeason: 'Kış/İlkbahar',
    imageUrl: require('../assets/images/Mercimek.jpg'),
    description: 'Kuraklığa dayanıklı, protein açısından zengin bir baklagil türüdür.'
  },
  {
    id: 11,
    name: 'Bakla',
    category: 'Baklagil',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'Kış/İlkbahar',
    imageUrl: require('../assets/images/Bakla.jpg'),
    description: 'Hem taze hem de kuru olarak tüketilebilen besleyici bir baklagil türüdür.'
  },
  {
    id: 12,
    name: 'Borulce',
    category: 'Baklagil',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Borulce.jpg'),
    description: 'Taze ve kuru olarak tüketilebilen, protein açısından zengin bir baklagil türüdür.'
  },

  // Endüstri Bitkileri (Industrial Crops)
  {
    id: 13,
    name: 'Seker_Pancari',
    category: 'Endüstri Bitkisi',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.5-7.5',
    climate: ['Ilıman'],
    waterNeeds: 'Yüksek',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Seker_Pancari.jpg'),
    description: 'Şeker üretiminin temel hammaddesi olan önemli bir endüstri bitkisidir.'
  },
  {
    id: 14,
    name: 'Tutun',
    category: 'Endüstri Bitkisi',
    soilType: ['Kumlu', 'Killi'],
    phRange: '5.5-6.5',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Tutun.jpg'),
    description: 'Sigara ve diğer tütün ürünlerinin hammaddesi olan endüstriyel bir bitkidir.'
  },
  {
    id: 15,
    name: 'Kenevir',
    category: 'Endüstri Bitkisi',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Kendir.jpg'),
    description: 'Lif ve tohum üretimi için yetiştirilen endüstriyel bir bitkidir.'
  },
  {
    id: 16,
    name: 'Keten',
    category: 'Endüstri Bitkisi',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Keten.jpg'),
    description: 'Lif ve yağ üretimi için yetiştirilen önemli bir endüstri bitkisidir.'
  },
  {
    id: 17,
    name: 'Kendir',
    category: 'Endüstri Bitkisi',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Kendir.jpg'),
    description: 'Lif üretimi için yetiştirilen endüstriyel bir bitkidir.'
  },

  // Yağlı Tohumlar (Oil Seeds)
  {
    id: 18,
    name: 'Aycicegi',
    category: 'Yağlı Tohum',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.5',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Aycicegi.jpg'),
    description: 'Yağ üretiminde kullanılan önemli bir yağlı tohum bitkisidir.'
  },
  {
    id: 19,
    name: 'Kolza',
    category: 'Yağlı Tohum',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'Kış/İlkbahar',
    imageUrl: require('../assets/images/Kolza.jpg'),
    description: 'Biyodizel ve yemeklik yağ üretiminde kullanılan önemli bir yağ bitkisidir.'
  },
  {
    id: 20,
    name: 'Aspir',
    category: 'Yağlı Tohum',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.5',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Düşük',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Aspir.jpg'),
    description: 'Kuraklığa dayanıklı, yağ üretiminde kullanılan bir yağ bitkisidir.'
  },
  {
    id: 21,
    name: 'Soya',
    category: 'Yağlı Tohum',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Yüksek',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Soya.jpg'),
    description: 'Protein ve yağ açısından zengin, çok yönlü kullanıma sahip bir yağ bitkisidir.'
  },
  {
    id: 22,
    name: 'Susam',
    category: 'Yağlı Tohum',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.0',
    climate: ['Sıcak'],
    waterNeeds: 'Orta',
    growingSeason: 'Yaz',
    imageUrl: require('../assets/images/Susam.jpg'),
    description: 'Yüksek kaliteli yağ üretiminde kullanılan önemli bir yağ bitkisidir.'
  },
  {
    id: 23,
    name: 'Hashas',
    category: 'Yağlı Tohum',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Düşük',
    growingSeason: 'Kış/İlkbahar',
    imageUrl: require('../assets/images/Hashas.jpg'),
    description: 'Yağ ve tohum üretimi için yetiştirilen özel bir yağ bitkisidir.'
  },

  // Yumrulu Bitkiler (Tuber Crops)
  {
    id: 24,
    name: 'Patates',
    category: 'Yumrulu Bitki',
    soilType: ['Kumlu', 'Killi'],
    phRange: '5.0-6.5',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Patates.jpg'),
    description: 'Türk mutfağının vazgeçilmez besin kaynaklarından biri olan önemli bir yumrulu bitkidir.'
  },
  {
    id: 25,
    name: 'Sogan',
    category: 'Yumrulu Bitki',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Sogan.jpg'),
    description: 'Türk mutfağının temel sebzelerinden biri olan önemli bir yumrulu bitkidir.'
  },
  {
    id: 26,
    name: 'Sarimsak',
    category: 'Yumrulu Bitki',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'Sonbahar/İlkbahar',
    imageUrl: require('../assets/images/Sarimsak.jpg'),
    description: 'Hem gıda hem de tıbbi amaçlarla kullanılan önemli bir yumrulu bitkidir.'
  },
  {
    id: 27,
    name: 'Salgam',
    category: 'Yumrulu Bitki',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Salgam.jpg'),
    description: 'Hem yaprağı hem de yumrusu tüketilebilen besleyici bir yumrulu bitkidir.'
  },

  // Yem Bitkileri (Forage Crops)
  {
    id: 28,
    name: 'Yonca',
    category: 'Yem Bitkisi',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.5-7.5',
    climate: ['Ilıman'],
    waterNeeds: 'Yüksek',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Yonca.jpg'),
    description: 'Hayvan beslenmesinde kullanılan yüksek protein içerikli önemli bir yem bitkisidir.'
  },
  {
    id: 29,
    name: 'Korunga',
    category: 'Yem Bitkisi',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.5',
    climate: ['Ilıman'],
    waterNeeds: 'Düşük',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Korunga.jpg'),
    description: 'Kuraklığa dayanıklı, hayvan beslenmesinde kullanılan önemli bir yem bitkisidir.'
  },
  {
    id: 30,
    name: 'Fig',
    category: 'Yem Bitkisi',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Fig.jpg'),
    description: 'Hayvan beslenmesinde kullanılan besleyici bir yem bitkisidir.'
  },
  {
    id: 31,
    name: 'Silajlik_Misir',
    category: 'Yem Bitkisi',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Yüksek',
    growingSeason: 'Yaz',
    imageUrl: require('../assets/images/Silajlik_Misir.jpg'),
    description: 'Silaj yapımında kullanılan özel yetiştirilen mısır çeşididir.'
  },

  // Bahçe Bitkileri (Garden Crops)
  {
    id: 32,
    name: 'Elma',
    category: 'Bahçe Bitkisi',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Elma.jpg'),
    description: 'Türkiye\'nin önemli meyve türlerinden biri olan elma, çeşitli iklim koşullarına uyum sağlayabilir.'
  },
  {
    id: 33,
    name: 'Uzum',
    category: 'Bahçe Bitkisi',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Uzum.jpg'),
    description: 'Hem sofralık hem de şarap üretiminde kullanılan önemli bir meyve türüdür.'
  },
  {
    id: 34,
    name: 'Kiraz',
    category: 'Bahçe Bitkisi',
    soilType: ['Killi', 'Kumlu-Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Kiraz.jpg'),
    description: 'Türkiye\'nin önemli ihraç ürünlerinden biri olan değerli bir meyve türüdür.'
  },
  {
    id: 35,
    name: 'Kayisi',
    category: 'Bahçe Bitkisi',
    soilType: ['Kumlu', 'Killi'],
    phRange: '6.0-7.0',
    climate: ['Ilıman', 'Sıcak'],
    waterNeeds: 'Orta',
    growingSeason: 'İlkbahar/Yaz',
    imageUrl: require('../assets/images/Kayisi.jpg'),
    description: 'Türkiye\'nin önemli ihraç ürünlerinden biri olan, hem taze hem de kuru olarak tüketilebilen bir meyve türüdür.'
  }
];
export const imageData = [
  { label: 'Bugday', uri: require('../assets/images/Bugday.jpg') },
    { label: 'YETISMEZ', uri: require('../assets/images/YETISMEZ.jpg') },
  { label: 'Arpa', uri: require('../assets/images/Arpa.jpg') },
  { label: 'Misir', uri: require('../assets/images/Misir.jpg') },
  { label: 'Cavdar', uri: require('../assets/images/Cavdar.jpg') },
  { label: 'Yulaf', uri: require('../assets/images/Yulaf.jpg') },
  { label: 'Tritikale', uri: require('../assets/images/Tritikale.jpg') },
  { label: 'Kaplica_Bugdayi', uri: require('../assets/images/Kaplica_Bugdayi.jpg') },
  { label: 'Nohut', uri: require('../assets/images/Nohut.jpg') },
  { label: 'Kuru_Fasulye', uri: require('../assets/images/Kuru_Fasulye.jpg') },
  { label: 'Mercimek', uri: require('../assets/images/Mercimek.jpg') },
  { label: 'Bakla', uri: require('../assets/images/Bakla.jpg') },
  { label: 'Borulce', uri: require('../assets/images/Borulce.jpg') },
  { label: 'Seker_Pancari', uri: require('../assets/images/Seker_Pancari.jpg') },
  { label: 'Tutun', uri: require('../assets/images/Tutun.jpg') },
  { label: 'Kenevir', uri: require('../assets/images/Kendir.jpg') },
  { label: 'Keten', uri: require('../assets/images/Keten.jpg') },
  { label: 'Kendir', uri: require('../assets/images/Kendir.jpg') },
  { label: 'Aycicegi', uri: require('../assets/images/Aycicegi.jpg') },
  { label: 'Kolza', uri: require('../assets/images/Kolza.jpg') },
  { label: 'Aspir', uri: require('../assets/images/Aspir.jpg') },
  { label: 'Soya', uri: require('../assets/images/Soya.jpg') },
  { label: 'Susam', uri: require('../assets/images/Susam.jpg') },
  { label: 'Hashas', uri: require('../assets/images/Hashas.jpg') },
  { label: 'Patates', uri: require('../assets/images/Patates.jpg') },
  { label: 'Sogan', uri: require('../assets/images/Sogan.jpg') },
  { label: 'Sarimsak', uri: require('../assets/images/Sarimsak.jpg') },
  { label: 'Salgam', uri: require('../assets/images/Salgam.jpg') },
  { label: 'Yonca', uri: require('../assets/images/Yonca.jpg') },
  { label: 'Korunga', uri: require('../assets/images/Korunga.jpg') },
  { label: 'Fig', uri: require('../assets/images/Fig.jpg') },
  { label: 'Silajlik_Misir', uri: require('../assets/images/Silajlik_Misir.jpg') },
  { label: 'Elma', uri: require('../assets/images/Elma.jpg') },
  { label: 'Uzum', uri: require('../assets/images/Uzum.jpg') },
  { label: 'Kiraz', uri: require('../assets/images/Kiraz.jpg') },
  { label: 'Kayisi', uri: require('../assets/images/Kayisi.jpg') },
];